server:
  port: 1800

spring:
  application:
    name: my-money-app
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/money
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
