server:
  port: 1800

cors-path: "*"

ssh-key:
  public: classpath:ssh_key/spring-rest-security.pub
  private: classpath:ssh_key/spring-rest-security

logging:
  level:
    org.springframework.web: INFO
  file: ./logs/application.log

spring:
  application:
    name: my-money-app
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/money
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

config:
  mail:
    username: "my.money.app0@gmail.com"
    password: "!JeffersonS2Victor!"
